cc_library(
	name = "hash",
	srcs = ["hash.cc"],
	hdrs = ["hash.h"],
)

cc_binary(
        name = "hash_test",
        srcs = ["hash_test.cc"],
        deps = [
                ":hash",
        ],
)

